gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/hostname: ${domain_name}.
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-source-ranges: "10.0.0.0/8"
    hosts:
      - host: ${domain_name}
        paths:
          - path: /
            pathType: Prefix
loki:
  storageConfig:
    aws:
      s3: s3://${storage_region}/${storage_s3_bucket}
      dynamodb:
        dynamodb_url: dynamodb://${storage_region}
  schemaConfig:
    configs:
      - from: 2020-09-07
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: ${dynamodb_table_prefix}
          period:
            24h
serviceAccount:
  create: true
  name: loki-sa
  annotations:
    eks.amazonaws.com/role-arn: ${service_account_role_arn}
