- name: "Install SonarQube 7.2.1"
  hosts: "all"
  become: True
  pre_tasks:
    - name: "install epel"
      package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: "present"
      when: ansible_distribution == 'RedHat'
  roles:
    - "../roles/lean_delivery.java"
    - "../roles/nginxinc.nginx"
    - "../roles/ansible-role-sonarqube"
    - "../roles/lean_delivery.zabbix_agent"
  vars:
    zabbix_agent_server: "10.130.115.160"
    zabbix_agent_serveractive: "10.130.115.160"
    zabbix_agent_hostname: ""
    sonar_store: "https://binaries.sonarsource.com/Distribution/sonarqube"
    sonar_nofile: 65536
    sonar_nproc: 2048
    sonar_log_level: "INFO"
    sonar_java_opts:
      web: "-server -Xmx2g -Xms2g"
      es: "-Xmx4g -Xms4g" 
      ce: "-Xmx4g -Xms4g"
    sonar_major_version: 7
    sonar_minor_version: 2.1
    sonar_db:
      type: "postgresql"
      port: 5432
      host: "sonarqube7.clyiioiw1agv.eu-central-1.rds.amazonaws.com"
      name: "sq_in"
      user: "sonar"
      password: "sonar"
      options: ""
    web:
      host: "localhost"
      port: 9000
      path: "/" 
    sonar_proxy:
      type: "nginx"
      port: 9999
      ssl: False
    sonar_plugins:
      - "https://github.com/checkstyle/sonar-checkstyle/releases/download/4.11/\
        checkstyle-sonar-plugin-4.11.jar"
      - "https://binaries.sonarsource.com/Distribution/sonar-html-plugin/\
        sonar-html-plugin-3.0.1.1444.jar"
      - "https://github.com/spotbugs/sonar-findbugs/releases/download/3.8.0/\
        sonar-findbugs-plugin-3.8.0.jar"
      - "https://github.com/pmayweg/sonar-groovy/releases/download/1.5/\
        sonar-groovy-plugin-1.5.jar"
      - "https://github.com/stevespringett/dependency-check-sonar-plugin/releases/download/1.1.1/\
        sonar-dependency-check-plugin-1.1.1.jar"
      - "https://github.com/racodond/sonar-jproperties-plugin/releases/download/2.5/\
        sonar-jproperties-plugin-2.5.jar"
      - "https://github.com/willemsrb/sonar-issueresolver-plugin/releases/download/\
        sonar-issueresolver-plugin-1.0.2/sonar-issueresolver-plugin-1.0.2.jar"
      - "https://binaries.sonarsource.com/Distribution/sonar-java-plugin/\
        sonar-java-plugin-5.7.0.15470.jar"
      - "https://binaries.sonarsource.com/Distribution/sonar-javascript-plugin/\
        sonar-javascript-plugin-4.2.1.6529.jar"
      - "https://binaries.sonarsource.com/Distribution/sonar-typescript-plugin/\
        sonar-typescript-plugin-1.8.0.3332.jar"
      - "https://binaries.sonarsource.com/Distribution/sonar-css-plugin/\
        sonar-css-plugin-1.0.2.611.jar"
      - "https://github.com/racodond/sonar-json-plugin/releases/download/2.3/\
        sonar-json-plugin-2.3.jar"
      - "https://github.com/SonarQubeCommunity/sonar-build-breaker/releases/download/2.2/sonar-build-breaker-plugin-2.2.jar"
    sonar_exclude_plugins:
      - "extensions/plugins/\
        sonar-java-plugin-5.4.0.14284.jar"
      - "extensions/plugins/\
        sonar-javascript-plugin-4.1.0.6085.jar"
      - "extensions/plugins/\
        sonar-typescript-plugin-1.7.0.2893.jar"

  post_tasks:
    - name: "start sonarqube"
      service: name="sonarqube" state="started"
    - name: "restart nginx"
      service: name="nginx" state="restarted"

