- src: lean_delivery.java
  version: 2.0.1

- src: lean_delivery.hybris_bootstrap_node
  version: 1.3.0

- src: lean_delivery.mysql
  version: 1.0.0

- src: lean_delivery.solr_standalone
  version: 1.2.5

- src: lean_delivery.solr_hybris_config
  version: 1.2.2

- src: lean_delivery.nodejs
  version: 1.2.0

- src: https://github.com/nginxinc/ansible-role-nginx
  version: "783d29639cce0a931589e67a1e2cb938b74dd1ef"

- src: openmicroscopy.ssl-certificate
  version: 0.3.1

- src: gantsign.intellij
  version: 5.10.2 
