{
 "title": "Marketplace authorization",
 "tags": [ "marketplace-auth" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Environment", "query": "PROD" }
  ]
 },
 "panels": [
  {
   "title": "Daily stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_registration_total{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\"}[$__range]))",
     "legendFormat": "Registrations"
    },
    {
     "expr": "sum(increase(auth_login_total{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\"}[$__range]))",
     "legendFormat": "Logins"
    },
    {
     "expr": "sum(increase(auth_refresh_total{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\"}[$__range]))",
     "legendFormat": "Relogin"
    },
    {
     "expr": "sum(increase(comm_otp_total{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\"}[$__range]))",
     "legendFormat": "OTP SMS"
    },
    {
     "expr": "sum(increase(visitor_oidc_total{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\"}[$__range]))",
     "legendFormat": "Visits"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", outcome=\"CLIENT_ERROR\", uri!=\"/**\"}[$__range]))",
     "legendFormat": "Validation errors"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", outcome=\"SERVER_ERROR\", uri!=\"/**\"}[$__range]))",
     "legendFormat": "Server errors"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(visitor_referral_total{env=\"$Environment\"}[1m]))",
     "legendFormat": "Referral visitors"
    },
    {
     "expr": "sum(increase(visitor_oidc_total{env=\"$Environment\"}[1m]))",
     "legendFormat": "OZON visitors"
    }
   ]
  },
  {
   "title": "Authorizations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(auth_login_total{env=\"$Environment\"}[1m]))",
     "legendFormat": "Login count"
    },
    {
     "expr": "sum(increase(auth_registration_total{env=\"$Environment\"}[1m]))",
     "legendFormat": "Registration count"
    },
    {
     "expr": "sum(increase(auth_blocked_total{env=\"$Environment\"}[1m]))",
     "legendFormat": "Blocked attempts"
    },
    {
     "expr": "sum(increase(auth_refresh_total{env=\"$Environment\"}[1m]))",
     "legendFormat": "Relogin count"
    }
   ]
  },
  {
   "title": "SMS communications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(comm_otp_total{env=\"$Environment\"}[1m])) or on() vector(0)",
     "legendFormat": "OTP SMS"
    },
    {
     "expr": "sum(increase(comm_reg_sms_total{env=\"$Environment\"}[1m])) or on() vector(0)",
     "legendFormat": "Registration SMS"
    },
    {
     "expr": "sum(increase(comm_sms_errors_total{env=\"$Environment\"}[1m])) or on() vector(0) ",
     "legendFormat": "Delivery errors"
    }
   ]
  },
  {
   "title": "Email communications",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(comm_rc_email_total{env=\"$Environment\"}[1m])) or on() vector(0)",
     "legendFormat": "Customer registration emails"
    },
    {
     "expr": "sum(increase(comm_sponsor_email_total{env=\"$Environment\"}[1m])) or on() vector(0)",
     "legendFormat": "Sponsor registration emails"
    },
    {
     "expr": "sum(increase(comm_email_errors_total{env=\"$Environment\"}[1m])) or on() vector(0)",
     "legendFormat": "Email errors"
    },
    {
     "expr": "sum(increase(comm_email_confirmation_total{env=\"$Environment\"}[1m])) or on() vector(0) ",
     "legendFormat": "Email verification success"
    }
   ]
  },
  {
   "title": "OTP use time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(user_otp_use_seconds_sum[1m]))/sum(rate(user_otp_use_seconds_count[1m]))",
     "legendFormat": "OTP use time, seconds"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{env=\"$Environment\", outcome=\"SERVER_ERROR\", service=\"marketplace-auth\"}[1m])) or on() vector(0)",
     "legendFormat": "500 errors"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{env=\"$Environment\", outcome=\"CLIENT_ERROR\", service=\"marketplace-auth\", uri!=\"/**\"}[1m])) or on() vector(0)",
     "legendFormat": "400 ERRORS"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", id=\"Eden Space\"})",
     "legendFormat": "Eden"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", id=\"Eden Space\"})",
     "legendFormat": "Eden max"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", id=\"Survivor Space\"})",
     "legendFormat": "Survivor"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", id=\"Survivor Space\"})",
     "legendFormat": "Survivor max"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", id=\"Tenured Gen\"})",
     "legendFormat": "Old"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"microservice-marketplace-auth-rukz\", env=\"PROD\", id=\"Tenured Gen\"})",
     "legendFormat": "Old max"
    }
   ]
  }
 ]
}