- hosts: all
  remote_user: ec2-user

  pre_tasks:
    - name: Update and install tools
      include_tasks: prepare.yaml

  roles:
    - role: "../../roles/github-actions/github-runner"
      tags:
        - github