- name: Install Automox agent on VMs
  hosts: all
  tasks:
   - name: Check InstanceId
     shell: curl http://169.254.169.254/latest/meta-data/instance-id
     register: instanceId

   - name: Check Region
     shell: curl http://169.254.169.254/latest/meta-data/placement/region
     register: region

#below: the tricky way. To get profile name, we need to pick ARN, and then extract profile name from its ARN
   - name: Check IAM instance profile
     shell: aws ec2 describe-instances --query 'Reservations[0].Instances[0].IamInstanceProfile.Arn' --output text --instance-id {{instanceId.stdout}} | cut -d '/' -f2 
     register: iam_profile_name
     delegate_to: localhost

   - name: Check role for received IAM instance profile
     shell: aws iam get-instance-profile --instance-profile-name {{ iam_profile_name.stdout }} --query 'InstanceProfile.Roles[0].Arn' --output text | cut -d '/' -f2
     register: iam_role_name
     delegate_to: localhost
  
   - name: Attach role policy to role detected
     shell: aws iam attach-role-policy --policy-arn arn:aws:iam::744058822102:policy/CORP-EC2SSMAdministration-ManagedPolicy --role-name {{ iam_role_name.stdout }}
     delegate_to: localhost

   - name: Check Flexera Server availability
     shell: ping -c 1 usnt00584.na.intranet.msd

  # I gave up, due to poor VPN speed this was impossible to achieve. I downloaded manually.
  #  - name: Obtain Flexera install package from S3
  #    shell: aws s3api get-object --bucket cloud-agents --key flexera/LATEST/managesoft-17.4.1-1.x86_64.rpm /var/tmp/{{ instanceId.stdout }}-managesoft-17.4.1-1.x86_64.rpm
  #    delegate_to: localhost

  #  - name: Upload install package to target machine
  #    copy:
  #      src: managesoft-17.4.1-1.x86_64.rpm
  #      dest: /var/tmp/managesoft-17.4.1-1.x86_64.rpm

   - name: Upload pkg to EC2
     unarchive:
       src: managesoft.tgz
       dest: /var/tmp    

   - name: Install Flexera package
     become: yes
     shell: rpm --upgrade --verbose --force /var/tmp/managesoft-17.4.1-1.x86_64.rpm

   - name: Tag instance
     shell: |
       aws ec2 create-tags --resources {{ instanceId.stdout }} --tags Key=ITAM-SAM,Value=Installed --region {{ region.stdout }}
       #aws ec2 create-tags --resources {{ instanceId.stdout }} --tags Key=Distro,Value=AmazonLinux --region {{ region.stdout }}
     delegate_to: localhost