---
- name: Ensure Runner Group exists
  become: true
  group:
    name: "{{ runner_group }}"
    state: present

- name: Create wheel group
  become: true
  group:
    name: wheel
    state: present


- name: Create Runner User
  become: true
  user:
    name: "{{ runner_user }}"
    groups: "{{ runner_group }},wheel"
    home: "/home/{{ runner_user }}"

- name: Add agent user to sudoers
  become: true
  template:
    src: 10-agent-user.j2
    dest: /etc/sudoers.d/10-agent-user

