---
- name: "Download and add the repository"
  become: True
  get_url:
    url: "{{ mysql_distr_url }}"
    dest: "/tmp"

- name: "Install mysql rpm from a downloaded file"
  become: True
  yum:
    name: "{{ mysql_distr_local }}"
    state: "present"

- name: "Install MySQL"
  become: True
  yum: 
    name: "mysql-server"
    state: "present"

- name: "Install python mysql bindings"
  become: True
  yum: 
    name: "MySQL-python"
    state: "installed"

- name: "Check that the my.cnf exists"
  stat:
    path: "~/.my.cnf"
  register: stat_result

- name: "Copy .my.cnf file with root password credentials to current user"
  template:
    src: "user.my.cnf.j2"
    dest: "~/.my.cnf"
    mode: "0600"

- name: "Copy my.cnf template file with settings"
  become: True
  template:
    src: "my.cnf.j2"
    dest: "/etc/my.cnf"
    backup: True
    
- name: "Start the mysqld service"
  become: True
  service:
    name: "mysqld"
    state: "started"
    enabled: False

- name: "Set root password"
  become: True
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  when: stat_result.stat.exists == False
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  notify: "Reload privilege tables in MySQL"

- meta: "flush_handlers"

- name: "Delete anonimous user"
  shell: "mysql -u {{ mysql_root_user }} -p{{ mysql_root_password }} -e \"DELETE FROM mysql.user WHERE User='';\""
  notify: "Reload privilege tables in MySQL"

- name: "Create database"
  mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_db_name }}"
    state: "present"
  notify: "Reload privilege tables in MySQL"

- name: "Create user"
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_pass  }}"
    priv: "{{ mysql_db_name }}.*:ALL,GRANT"
    host: ""
    state: "present"
  notify: "Reload privilege tables in MySQL"
