CREATE DATABASE IF NOT EXISTS ga_builds_db;
CREATE USER 'ga_builds'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON `ga_builds_db`.* TO 'ga_builds'@'%';
FLUSH PRIVILEGES;
USE `ga_builds_db`;

CREATE TABLE IF NOT EXISTS `dev-rel` (
	`run_id` BIGINT NOT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
        `build_number` INT NOT NULL,
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `support-rel` (
	`run_id` BIGINT NOT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
        `build_number` INT NOT NULL,
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `support-dev` (
	`run_id` BIGINT NOT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
        `build_number` INT NOT NULL,
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `support-hotfix` (
	`run_id` BIGINT NOT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
        `build_number` INT NOT NULL,
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `prod` (
	`run_id` BIGINT NOT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
        `build_number` INT NOT NULL,
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dev-dcm` (
	`run_id` BIGINT NOT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
        `build_number` INT NOT NULL,
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `deploy_status` (
	`env_name` VARCHAR(6) NOT NULL,
	`release` VARCHAR(100) NOT NULL,
	`release_link` VARCHAR(200) DEFAULT NULL,
	`log_link` VARCHAR(300) DEFAULT NULL,
	`gh_user` VARCHAR(60) DEFAULT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
       	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`env_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `deploy_history` (
	`run_id` BIGINT NOT NULL,
	`env_name` VARCHAR(6) NOT NULL,
	`release` VARCHAR(100) NOT NULL,
	`release_link` VARCHAR(200) DEFAULT NULL,
	`log_link` VARCHAR(300) DEFAULT NULL,
	`gh_user` VARCHAR(60) DEFAULT NULL,
	`status` VARCHAR(12) DEFAULT NULL,
       	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
