---
# Apply common configuration
- hosts: all
  vars:
    docker_container_size: "20G"
  remote_user: centos

# Just to make things easy
  pre_tasks:
    - name: "Disable Selinux"
      become: True
      selinux:
        state: "disabled"

    - name: Update and install tools
      include_tasks: prepare.yml

  roles:
    - role: '../roles/lean_delivery.docker'
      vars:
        docker_version: "18.09.2"
        docker_users: 
          - "centos"
  post_tasks:
    - name: Tune docker daemon
      include_tasks: tune.yml
      vars:
        file_size_mb: 64
        max_files: 2
