---
- name: Install Nexus
  hosts: all
  become: yes

  vars:
    nexus_version: "3.30.0-01"
    nexus_timezone: "UTC"
    nexus_admin_password: ""
    nexus_anonymous_access: true
    nexus_api_hostname: "{{ ansible_default_ipv4.address }}"
    nexus_public_hostname: "nexus-eu"
    nexus_branding_header: "Amway Nexus EU"
    
    # see this link before changing these parameters
    # https://help.sonatype.com/repomanager3/system-requirements#SystemRequirements-Memory
    nexus_min_heap_size: "2703M"
    nexus_max_heap_size: "{{ nexus_min_heap_size }}"
    nexus_max_direct_memory: "2703M"
    
    nexus_delete_default_repos: true
    nexus_delete_default_blobstore: true
    nexus_privileges:
      - name: all-repos-read
        description: "Read & Browse access to all repos"
        repository: "*"
        actions:
          - read
          - browse
    nexus_roles:
      - id: developers
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
        roles: []
    nexus_local_users:
      - username: anonymous
        first_name: Anonymous
        password: K!V7k7rD4VSQKmFZ2AQfHgqchrDhmse4eauUTDwCZMmBkASrtaDKhn4s3frL9fVTnHgsLcD6a7jCBx8HBCdr3JUwbwjzRS7waHU8Hjkzeqv3wW9d4Rkeh8NPL3jMPbC2L!
        last_name: User
        email: anonymous@example.org
        roles:
           - developers
  roles:
    - role: "../roles/lean_delivery.java"
      vars:
        java_distribution: oracle_java
        java_package: jre
        java_major_version: 8
        java_tarball_install: true
        transport: "web"
        transport_web: "https://nexus.hybris.eia.amway.net/repository/static-files/static-dev/jre-8u131-linux-x64.tar.gz"
    - role: "../roles/ansible-thoteam.nexus3-oss"
