---
# Apply common configuration
- hosts: "all"
  remote_user: "ec2-user"

  # Just to make things easy
  pre_tasks:

    - name: Update and install tools
      include_tasks: prepare.yaml

    # - name: Disable Selinux
    #   become: True
    #   selinux:
    #     state: "disabled"

  roles:
    - role: "../../roles/github-actions/github-runner"
      tags:
        - github

    - role: "../../roles/lean_delivery.java"
      tags:
        - java

    - role: "../../roles/gantsign.maven"
      vars:
        maven_redis_sha256sum: ''
      tags:
        - java

    # - role: "../../roles/github-actions/autotest-agent"
    #   become: True
    #   tags:
    #     - autotests

    - role: '../../roles/lean_delivery.docker'
      vars:
#        docker_version: "19.03.15"
#        docker_version: "18.09.1"
        docker_users:
          - github
          - ec2-user
      tags:
        - docker
