---
# Apply common configuration
- hosts: "all"
  remote_user: "centos"
# Just to make things easy
  pre_tasks:
    - name: "Disable Selinux"
      become: True
      selinux:
        state: "disabled"

    - name: "Create parent datadir for mysql"
      become: True
      file:
        path: /opt/media
        state: directory
        owner: root
        mode: 0755
        
  vars:
    bamboo_agent_user: "bamboo"
    bamboo_agent_group: "bamboo"      
    bamboo_agent_application_folder: "/var/bamboo-agent"      

  roles:
  - role: '../roles/lean_delivery.java'
    java_package: jdk
    transport: "web"
    transport_web: "https://nexus.hybris.eia.amway.net/repository/static-files/static-dev/jdk-8u131-linux-x64.tar.gz"
    tags:
      - java

  - role: '../roles/gantsign.maven'
    maven_version: '3.2.5'
    tags:
      - java
      
  - role: '../roles/shelleg.gradle' 
    become: True
    tags:
      - java
  
  - role: '../roles/lean_delivery.nodejs'
    nodejs_branch: 8
    nodejs_version: "8.13.0"
    build_tools: True    
    tags:
      - nodejs

  - role: '../roles/sonarqube-scanner'
    SONARSCANNER_VER: "3.3.0.1492"
    SONARSCANNER_ZIP: "sonar-scanner-cli-{{ SONARSCANNER_VER }}-linux.zip"
    SONARSCANNER_UNZIP: "sonar-scanner-{{ SONARSCANNER_VER }}-linux"
    SONARSCANNER_URL: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{ SONARSCANNER_VER }}-linux.zip"
    tags:
      - sonar
  
  - role: '../roles/lean_delivery.mysql'
    # role params to rewrite role's vars
    mysql_username: "mysql"
    mysql_groupname: "mysql"
    mysql_datadir: "/opt/media/mysql"
    mysql_version: 5.6
    mysql_sql_mode: "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
    mysql_root_password: "{{ MYSQL_PASSWORD }}"
    mysql_bind_address: "127.0.0.1"
    mysql_max_connections: 400
    mysql_innodb_buffer_pool_size: "5674M"
    mysql_innodb_flush_log_at_trx_commit: 0
    additional_parameters:
      - name: "character_set_server"
        value: "utf8"
      - name: "default_storage_engine"
        value: "InnoDB"
    tags:
      - mysql
  
  - role: '../roles/bamboo-agent'
    become: True
    bamboo_agent_spot: True
    bamboo_agent_remote: True
    bamboo_cert_url: "amway-prod.tt.com.pl/bamboo"
    bamboo_master_url: "https://amway-prod.tt.com.pl/bamboo"
    bamboo_master_version: "6.6.3"
    bamboo_agent_data_folder: "/var/bamboo-agent"
    bamboo_agent_jvm_xms: "512"
    bamboo_agent_jvm_xmx: "1024"
    bamboo_agent_start_timeout: "1440"
    bamboo_agent_timezone: "Europe/Warsaw"
    bamboo_java_home: "/usr/java/jdk1.8.0_131"
    tags:
      - bamboo
      
  - role: '../roles/ci-pull-requests-prepare'
    become: True
    ci_spot_user: "{{ bamboo_agent_user }}"
    ci_spot_bamboo_agent_application_folder: "{{ bamboo_agent_application_folder }}"
    db_name: "hybris"
    db_user: "hybris"
    db_password: "hybris"
    db_root_password: "{{ MYSQL_PASSWORD }}"
    hybris_nexus_url: "https://nexus.hybris.eia.amway.net/repository/static-files/hybris"
    hybris_artifact_dest: "{{ bamboo_agent_application_folder }}"
    hybris_artifact_list:
       - "last_6.6.0.19.zip"
       - "last_6.6.zip"   
    tags:
      - mysql
      - bamboo
