- src: lean_delivery.java
  version: 2.2.0

- src: lean_delivery.mysql
  version: 1.6.0

#- src: lean_delivery.hybris_bootstrap_node
#  version: 1.0
  
- src: gantsign.maven
  version: 5.3.0

- src: shelleg.gradle
  version: v1.1.3
 
# should be replaced with opensource role when it's released by Lean Delivery
- src: git@git.epam.com:dip-roles/sonarqube-scanner.git
  scm: git
  version: master 

- src: lean_delivery.nodejs
  version: 1.2.1
