- hosts: all
  remote_user: centos
  vars_files:
    - ./vars/all.yaml

  pre_tasks:

    - name: "Disable Selinux"
      become: true
      selinux:
        state: "disabled"

    - name: Install CloudWatch agent
      become: yes
      yum:
        name:
          - collectd
        state: present
  
  tasks:
    - name: Download CloudWatch RPM 
      become: true
      shell: wget https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm

    - name: Install CloudWatch agent
      become: true
      shell: rpm -U ./amazon-cloudwatch-agent.rpm
    
    - name: Copy script to run service
      become: true
      copy:
        src: ./install.sh
        dest: "/home/{{ runner_user }}/{{ runner_workdir }}"
        owner: "{{ runner_user }}"
        mode: u=rwx,g=rx,o=r

    - name: Copy systemd cfg for the service
      become: true
      copy:
        src: ./github-runner.service
        dest: "/etc/systemd/system/github-runner.service"
        owner: root
        mode: u=rw,g=r,o=r

    - name: Ensure logdir exists
      become: yes
      file:
        path: /var/log/github-runner/
        state: directory
        group: root
        owner: root
        mode: 0660

    - name: Ensure logfile exists
      become: true
      copy:
        content: ""
        dest: /var/log/github-runner/log.txt
        group: root
        owner: root
        mode: 0660

    - name: Copy rsyslogd cfg file
      become: true
      copy:
        src: ./rsyslogd.conf
        dest: "/etc/rsyslog.d/github-runner.conf"
        owner: root
        mode: u=rw,g=r,o=r

    #File we use in this step was generated by running config wizard, placed in same dir as destination
    - name: Copy CloudWatch Agent cfg
      become: true
      copy:
        src: ./cloudwatch-agent-config.json
        dest: "/opt/aws/amazon-cloudwatch-agent/bin/config.json"
        owner: root
        mode: u=rw,g=r,o=r
    - name: Configure CloudWatch Agent service
      become: yes
      shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json