apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "10254"
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    app.kubernetes.io/name: alb-ingress-controller
