---
- name: Assign capacity reservaton to instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    capacity_reservation_id: "{{ lookup('env', 'CAPACITY_RESERVATION_ID') }}"

  roles:
    - role: "../roles/deployment/capacity-reservation-prepare"
      vars:
        capacity_reservation_id: "{{capacity_reservation[environment_name|lower]}}"
      when:
        - (environment_name | lower) in capacity_reservation

