- hosts: all
  remote_user: ec2-user

  pre_tasks:

    - name: Disable SELinux by modifying config file
      become: yes
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        state: present
      notify: Reboot server

    - name: Update and Install required packages
      block:
        - name: Perform yum update
          yum:
            name: "*"
            state: "latest"

        - name: Install amazon-linux-extras packages
          shell: "amazon-linux-extras install {{ item }}"
          loop: "{{ amazon_packages }}"

        - name: Install policycoreutils-python package
          yum:
            name: policycoreutils-python
            state: present
      become: yes
    - name: Install HashiCorp GPG key
      rpm_key:
        state: present
        key: https://rpm.releases.hashicorp.com/gpg
      become: yes

    - name: Add HashiCorp repository
      yum_repository:
        name: hashicorp
        description: HashiCorp Linux repository
        baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/2/$basearch/stable
        gpgcheck: yes
        enabled: yes
      become: yes

    - name: Install Terraform
      yum:
        name: terraform
        state: present
      become: yes
        
    - name: Update and install tools
      include_tasks: prepare.yaml

  roles:
    - role: "../../roles/github-actions/github-runner"
      tags:
        - github
  