---
- name: Manage solr nodes
  hosts: all
  tasks:
  - name: Restart solr service
    command: sudo /bin/systemctl restart solr

  - name: Rediscover systemd service facts
    service_facts:      

  - name: Verify that solr service is running
    assert:
     that:
       - ansible_facts.services["solr.service"].state == "running"
     fail_msg: Failed to start solr service
     success_msg: Solr service has been started successfully      
