---
- name: Deploy Product Labeling microservice
  hosts: all
  tasks:
    - name: Get certificate from Vault
      block:
       - name: "Get certificate from Vault"
         set_fact:
           cprocsp_crt: "{{ lookup('hashi_vault', 'secret={{ vault_crt_kv_path }} auth_method=userpass username={{ vault_user }} password={{ vault_password }}') }}"

       - name: "Copy amway.pfx certificate to shared volume"
         copy:
           content: "{{ cprocsp_crt['pfx'] | b64decode }}"
           dest: "{{ docker_env_cer_mnt_path }}/amway.pfx"
           checksum: "{{ amway_dev_crt_checksum }}"
           unsafe_writes: True

      become: True
      when: not isProd
      tags:
        - get-certificate-vault

    - name: Get production certificate form AWS parameter store
      block:
       - name: Get first part of the certificate in base64
         set_fact:
           amway_prod_pfx_pt1: "{{ lookup('aws_ssm', '/production/microservices/product-labeling/amway-pfx-part1' ) }}"

       - name: Get second part of the certificate in base64
         set_fact:
           amway_prod_pfx_pt2: "{{ lookup('aws_ssm', '/production/microservices/product-labeling/amway-pfx-part2' ) }}"

       - name: "Copy amway.pfx certificate to shared volume"
         copy:
           content: "{{ '\n' .join((amway_prod_pfx_pt1, amway_prod_pfx_pt2)) | b64decode }}"
           dest: "{{ docker_env_cer_mnt_path }}/amway.pfx"
           checksum: "{{ amway_prod_crt_checksum }}"

      become: True
      when: isProd
      tags:
        - get-certificate-aws-ssm

- name: Install filebeat
  hosts: all
  roles:
    - role: '../roles/elastic.beats'
      when: LogsEnabled
      become: True
      tags:
        - filebeat-logs

- name: Launch docker conrainer on dev nodes
  hosts: all
  tasks:
    - include_tasks: run-docker-container.yml
      vars:
        docker_env_cprocsp_lic_number: "{{ lookup('hashi_vault', 'secret={{ vault_lic_kv_path }} auth_method=userpass username={{ vault_user }} password={{ vault_password }}') | json_query('lic') }}"
      when: not isProd
      tags:
        - deploy-on-dev-nodes

- name: Launch docker container on first node
  hosts: pl_node1
  tasks:
    - include_tasks: run-docker-container.yml
      vars:
        docker_env_cprocsp_lic_number: "{{ lookup('aws_ssm', '/production/microservices/product-labeling/cprocsp_license_01' ) }}"
      when: isProd
      tags:
        - deploy-on-first-node   

- name: Launch docker container on second node
  hosts: pl_node2
  tasks:
    - include_tasks: run-docker-container.yml
      vars:
        docker_env_cprocsp_lic_number: "{{ lookup('aws_ssm', '/production/microservices/product-labeling/cprocsp_license_02' ) }}"
      when: isProd  
      tags:
        - deploy-on-second-node  

- name: Launch docker container on third node
  hosts: pl_node3
  tasks:  
    - include_tasks: run-docker-container.yml
      vars:
        docker_env_cprocsp_lic_number: "{{ lookup('aws_ssm', '/production/microservices/product-labeling/cprocsp_license_03' ) }}"
      when: isProd 
      tags:
        - deploy-on-third-node  
