config:
  clients:
    - url: ${loki_clients_url}
  snippets:
    extraScrapeConfigs: |
      - job_name: nginx
        static_configs:
          - targets:
              - localhost
            labels:
              job: nginx
              agent: promtail
              __path__: /var/log/nginx/analytics*log
        pipeline_stages:
          - json:
              expressions:
                http_user_agent:
                request_uri:
          - drop:
              source: http_user_agent
              expression: "(bot|Bot|RSS|Producer|Expanse|spider|crawler|Crawler|Inspect|test)"
          - drop:
              source: request_uri
              expression: "/(assets|img)/"
          - drop:
              source: request_uri
              expression: "/(robots.txt|favicon.ico|index.php)"
          - drop:
              source: request_uri
              expression: "(.php|.xml|.png)$"
