stages:
  - creds-check
  - lint

creds-check:
  stage: creds-check
  image: centos:7.6.1810
  script:
    - os_name=$(uname | awk '{print tolower($1)}')
    - curl -o cred-alert-cli https://s3.amazonaws.com/cred-alert/cli/current-release/cred-alert-cli_${os_name}
    - chmod 755 cred-alert-cli
    - rm -f ./terraform/selenoid-consul/ssh_key/consul-server
    - ./cred-alert-cli scan -f .
  tags:
    - gitlab-runner


terraform_lint:
  stage: lint
  image:
    name: hashicorp/terraform:0.11.13
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - export ERROR=0
    - for TFDIR in $(find . -type f -name '*tf' | sed -r 's|/[^/]+$||' |sort |uniq); do terraform fmt -check=true $TFDIR; if [[ $? -ne 0 ]]; then ERROR=1 ; fi; done
    - for TFDIR in $(find . -type f -name '*tf' | sed -r 's|/[^/]+$||' |sort |uniq); do terraform validate -check-variables=false $TFDIR; if [[ $? -ne 0 ]]; then ERROR=1 ; fi; done
    - exit $ERROR
  tags:
    - gitlab-runner
