- name: ansible-role-ggr
  src: https://github.com/lean-delivery/ansible-role-ggr.git
  version: be0c2b724b42fae20a79d0ea4f2620a3656991a2
- name: ansible-consul
  src: https://github.com/brianshumate/ansible-consul.git
  version: 4507528909cfd6a30295f952ce721220514bb605
- name: ansible-role-selenoid
  src: https://github.com/lean-delivery/ansible-role-selenoid.git
  version: 2903bd48b0b6c43bd530a888f195e3b6dc43c4e5
- name: ansible-role-consul-template
  src: https://github.com/lean-delivery/ansible-role-consul-template.git
  version: 4b4dd56a7dcbc14650fbacd3680a0328f0fb4066