---
- name: "Create database"
  mysql_db:
    login_user: "root"
    login_password: "{{ db_root_password }}"
    name: "{{ hybris_db_name }}"
    state: "present"

- name: Create hybris user
  mysql_user:
    name: "{{ hybris_db_user }}"
    password: "{{ hybris_db_password }}"
    login_user: "root"
    login_password: "{{ db_root_password }}"
    priv: "*.*:ALL,GRANT"
    host: localhost  

- name: Create directory for media
  become: True
  file:
    path: "/opt/media"
    state: "directory"
    owner:  "{{ runner_user }}"
    group: "{{ runner_group }}"

- name: Create directory for se-tools
  become: True
  file:
    path: "/opt/se-tools"
    state: "directory"

- name: Add h-wrap scripts
  become: True
  template: 
    src: "h-wrap.py.j2"
    dest: "/opt/se-tools/h-wrap.py"
    owner: "root"
    group: "root"
    mode: '755'

- name: Create directory for junit_xml_output lib 
  become: True
  file:
    path: "/opt/se-tools/junit_xml_output"
    owner: "root"
    group: "root"
    state: "directory"

- name: Add junit_xml_output lib
  become: True
  template: 
    src: "__init__.py.j2"
    dest: "/opt/se-tools/junit_xml_output/__init__.py"
    owner: "root"
    group: "root"
    mode: '755'

- name: Add rules
  become: True
  template: 
    src: "rules.j2"
    dest: "/opt/se-tools/rules"
    owner: "root"
    group: "root"

- name: "Update npm to version {{ npm_version }}"
  become: True
  npm:
    name: npm
    version: "{{ npm_version }}"
    global: yes      

- name: Create dir for hybris download
  become: True
  file:
    path: "{{ hybris_artifact_dest }}"
    state: "directory"
    owner: "{{ runner_user }}"
    group: "{{ runner_group }}"

- name: Download hybris artifact from nexus
  become: True
  get_url:
   url: "{{ hybris_nexus_url }}/{{ item }}"
   dest: "{{ hybris_artifact_dest }}"
   mode: "0644"
   owner: "{{ runner_user }}"
   group: "{{ runner_group }}"
   checksum: "md5:{{ hybris_nexus_url }}/{{ item }}.md5"
  loop: "{{ hybris_artifact_list }}"
  register: hybris_artifact_downloaded
  until: hybris_artifact_downloaded is succeeded
  retries: 3
  delay: 2
 
