---
roles:
  - src: lean_delivery.java
    version: 2.0.1

  - src: lean_delivery.hybris_bootstrap_node
    version: 1.6.0

  - src: lean_delivery.zabbix_agent
    version: 1.0.0

  - src: lean_delivery.mysql
    version: 1.6.0

  - src: git@git.epam.com:dip-roles/filebeat-multiline.git
    scm: git
    version: master
      
  - src: ansibleshipyard.ansible-zookeeper
    version: 0.23.0

  - src: lean_delivery.nodejs
    version: 1.2.1

  - src: lean_delivery.solr_standalone
    version: 1.2.3

  - src: lean_delivery.solr_hybris_config
    version: 1.2.2
