---
- name: "create tdump.sh"
  become: True
  template:
    src: "tdump.sh.j2"
    dest: "/opt/tdump.sh"
    mode: "0755"
    owner: "centos"
    group: "centos"

- name: "make dir"
  become: True
  file:
    path: "/opt/tdumps"
    owner: "root"
    group: "root"
    state: "directory"
    
- name: "mount directory"
  become: True
  command: "mount 10.130.115.53:/home/storage/tdumps /opt/tdumps"
   
- name: "run file"
  become: True
  command: runuser -l hybris -c '/opt/tdump.sh'
  
- name: "check service status"
  become: True
  service:
    name: "crond"
    state: "started"
    
- name: "add cron line"
  become: "True"
  command: sed -i '$ a */10 * * * * hybris /opt/tdump.sh' /etc/crontab


