- name: "Create a script mediatype (skype)"
  zabbix_mediatype:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
    name: "skype"
    type: "script"
    script_name: 'chatbot.php'
    script_params:
      - "{ALERT.SENDTO}"
      - "{ALERT.SUBJECT}"
      - "{ALERT.MESSAGE}"


- name: "Create notification action"
  zabbix_action:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
    name: "Send alerts to Zabbix Admins"
    event_source: 'trigger'
    state: present
    esc_period: 60
    status: enabled
    conditions:
      - type: "trigger_severity"
        operator: ">="
        value: "Information"
      - type: "time_period"
        operator: "in"
        value:  "{{ notification_time_range }}"
    operations:
      - type: send_message
        subject: "{TRIGGER.STATUS}: {TRIGGER.NAME} on {HOST.NAME}"
        message: '<a href="http://{{ apache_server_name }}/zabbix.php?action=acknowledge.edit&acknowledge_type=1&eventids[]={EVENT.ID}">Set acknowledge</a>'
        media_type: 'All'
        send_to_groups:
          - "Zabbix administrators"
    recovery_operations:
      - type: send_message
        subject: "{TRIGGER.STATUS}: {TRIGGER.NAME} on {HOST.NAME}"
        message: '<a href="http://{{ apache_server_name }}/zabbix.php?action=acknowledge.edit&acknowledge_type=1&eventids[]={EVENT.ID}">Set acknowledge</a>'
        media_type: 'All'
        send_to_groups:
          - "Zabbix administrators"
