- src: lean_delivery.java
  version: 7.1.0

- src: lean_delivery.hybris_bootstrap_node
  version: 1.6.0

- src: lean_delivery.mysql
  version: 2.0.0

- src: lean_delivery.solr_standalone
  version: 1.2.6

- src: lean_delivery.solr_hybris_config
  version: 1.2.2

- src: lean_delivery.nodejs
  version: 1.2.1

- src: https://github.com/nginxinc/ansible-role-nginx
  version: "783d29639cce0a931589e67a1e2cb938b74dd1ef"

- src: openmicroscopy.ssl-certificate
  version: 0.3.1

