---
- name: Yum install
  become: True
  block:
    - name: Yum update
      yum:
        name: '*'
        state: latest
      when:
        - misc_update_all

    - name: Add Zabbix repo
      yum:
        name: "https://repo.zabbix.com/zabbix/{{ zabbix_server_version }}/rhel/7/x86_64/zabbix-release-{{ zabbix_server_version }}-2.el7.noarch.rpm"
        state: present

    - name: Install zabbix server
      yum:
        name:
          - zabbix-agent
          - zabbix-server-mysql
          - zabbix-java-gateway
        state: present

    - name: Install epel repo
      yum:
        name: epel-release
        state: present

    - name: Install pip
      yum:
        name: python-pip
        state: present

    - name: Install python mysql client to allow mysql_db and mysql_user ansible module execution
      pip:
        name: 
          - PyMySQL==0.10.1
        state: present    

    - name: Install additional packages
      when: misc_install_tools
      yum:
        name: "{{ additional_packages }}"
        state: present
  tags:
    - rpm
