---
- name: Yum install
  become: True
  block:
    - name: Yum update
      yum:
        name: '*'
        state: latest
      when: misc_update_all

    - name: Add Zabbix repo
      yum:
        name: "https://repo.zabbix.com/zabbix/{{ zabbix_server_version }}/rhel/7/x86_64/zabbix-release-{{ zabbix_server_version }}-2.el7.noarch.rpm"
        state: present

    - name: Install zabbix web
      yum:
        name:
          - zabbix-web-mysql
        state: present

    - name: Install epel repo
      yum:
        name: epel-release
        state: present
      when: misc_install_tools

    - name: Install additional packages
      yum:
        name: "{{ additional_packages }}"
        state: present
      when: misc_install_tools
  tags:
    - rpm
