- name: Copy config files
  become: True
  block:
    - name: Copy zabbix-web config file
      template:
        src: zabbix.conf.php.j2
        dest: /etc/zabbix/web/zabbix.conf.php
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
        mode: 0640
    - name: copy aapache VirtualHost template
      template:
        src: vhost.conf.j2
        dest: /etc/httpd/conf.d/zabbix.conf
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
        mode: 0640
  tags:
    - zabbix

- name: Start httpd
  become: True
  systemd:
    name: httpd
    enabled: yes
    state: started
  tags:
    - zabbix
