# Zabbix Server
zabbix_server_address: localhost
zabbix_server_port: 10051
zabbix_server_name: zabbix-server

# MySQL 
mysql_server_address: 127.0.0.1
mysql_server_port: 3306
mysql_zabbix_database: zabbix
mysql_zabbix_username: zabbix
mysql_zabbix_password: zabbix

# Apache
apache_listen_address: "*"
apache_listen_port: 80
apache_server_name: zabbix.example.com
apache_server_aliases: [ "www.zabbix.example.com", "monitoring.example.com" ]

php_value_max_execution_time: 300
php_value_memory_limit: 128M
php_value_post_max_size: 16M
php_value_upload_max_filesize: 16M
php_value_max_input_time: 300
php_value_max_input_vars: 10000
php_value_timezone: Europe/Moscow

# Misc
misc_install_tools: False
additional_packages: ["jq", "git", "joe", "vim", "tmux", "htop", "iotop", "tcpdump", "sysstat"]
misc_grafana_port: 3000
