---
- name: Override vars for local agent
  set_fact:
    bamboo_agent_user: "{{ bamboo_master_user }}"
  when:
    bamboo_agent_remote|bool == False

- name: Copy cleanup scripts
  template:
    src: bamboo/bamboo_cleanup.sh.j2
    dest: /root/bamboo_cleanup.sh
    mode: 0755

- name: Crontab entry for bamboo cleanup script
  cron:
    name: bamboo agent cleanup
    special_time: daily
    state: present
    job: /root/bamboo_cleanup.sh

- name: Populate PATH environment variable
  template:
    src: bamboo/bambooagent.sh.j2
    dest: /etc/profile.d/bambooagent.sh

- name: Add docker group
  group:
    name: docker
    state: present

- name: Ensure bamboo agent user is member of docker
  user:
     name: "{{ bamboo_agent_user }}"
     shell: /bin/bash
     groups: docker
     append: True
 