controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    internal:
      enabled: true
      annotations:
        # Create internal ELB
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
