---
- name: "install ansible selinux support library:"
  become: True
  package:
    name: "libselinux-python"
    state: "present"

- name: "install ansible selinux configure libraries"
  become: True
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - policycoreutils-python
    - libsemanage-python
  when: ansible_selinux.status == "enabled"

- name: "enable connections to http port"
  become: True
  seport: 
    ports: "{{ solr_port }}" 
    proto: "tcp"
    setype: "http_port_t"
    state: "present"
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode != "disabled"
