- hosts: all
  remote_user: centos

  pre_tasks:
    - name: "Disable Selinux"
      become: true
      selinux:
        state: "disabled"

    - name: Update and install tools
      include_tasks: prepare.yaml

  roles:
    - role: "../../roles/github-actions/github-runner"
      tags:
        - github

    - role: '../../roles/sonar-scanner'
      tags:
        - sonar

    - role: '../../roles/lean_delivery.docker'
      vars:
        docker_version: "18.09.2"
        docker_users:
          - github
          - centos
      tags:
        - docker
