---
- name: "Download jrebel artifact"
  get_url:
    url: "{{ jrebel_artifact_url }}/{{ jrebel_artifact_name }}"
    dest: "{{ jrebel_download_path }}/{{ jrebel_artifact_name }}"
  until: file_downloaded is succeeded
  retries: 3
  delay: 2
  register: file_downloaded
  delegate_to: "localhost"
  connection: "local"

- name: "Install jrebel"
  unarchive:
    src: "{{ jrebel_download_path }}/{{ jrebel_artifact_name }}"
    dest: "{{ jrebel_dest_path }}"
    owner: "{{ jrebel_user }}"
    group: "{{ jrebel_group }}"
    mode: 0755
  become: True
