---
- name: Check if we already have Sonar Scanner directory
  stat:
    path: "{{ sonar_scanner_dir  }}"
  register: sonar_dir

- include: install-scanner.yml
  when: sonar_dir.stat.isdir is not defined

- name: Creating a symbolic link to Sonar Scanner directory
  become: true
  file:
    src: "{{ sonar_scanner_dir }}"
    dest: "{{ sonar_scanner_link }}"
    state: link

- name: Add PATH entry in profile.d
  become: true
  template:
    src: sonar-scanner.sh.j2
    dest: /etc/profile.d/sonar.sh
    mode: 0755
