all:
  hosts:
    solrnode-0:
      ansible_host: <ip address>
    solrnode-1:
      ansible_host: <ip address>
    zknode-3:
      ansible_host: <ip address>
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
  children:
    solr:
      hosts:
        solrnode-0:
        solrnode-1:
    zookeeper:
      hosts:
        solrnode-0:
        solrnode-1:
        zknode-3:
