- src: lean_delivery.java
  version: 2.2.0

- src: lean_delivery.mysql
  version: 1.6.0

- src: gantsign.maven
  version: 5.3.0

- src: shelleg.gradle
  version: v1.1.3
 
- src: lean_delivery.nodejs
  version: 1.2.1

- src: lean_delivery.docker                                                                                                       
  version: 2.0.4    
