- name: Install java
  hosts: all
  become: yes
  vars:
    transport: "web"
    transport_web: "https://nexus.hybris.eia.amway.net/repository/static-files/static-dev/jre-8u131-linux-x64.tar.gz"
  roles:
    - { role: "../roles/lean_delivery.java" }

- name: Install zookeeper
  hosts: zookeeper
  become: yes
  vars:
    zookeeper_version: 3.4.13
    zookeeper_url: "http://archive.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz"
    client_port: 2181
    init_limit: 5
    sync_limit: 2
    tick_time: 2000
    zookeeper_cluster_ports: "2888:3888"
    data_dir: "/var/lib/zookeeper"
    log_dir: "/var/log/zookeeper"
    zookeeper_dir: "/opt/zookeeper"
    zookeeper_conf_dir: "{{ zookeeper_dir }}"
    zookeeper_tarball_dir: "/opt/"
    zookeeper_hosts:
    - host: "{{ hostvars['solrnode-0']['ansible_default_ipv4']['address'] }}"
      id: 1
    - host: "{{ hostvars['solrnode-1']['ansible_default_ipv4']['address'] }}"
      id: 2
    - host: "{{ hostvars['zknode-3']['ansible_default_ipv4']['address'] }}"
      id: 3
  pre_tasks:
    - name: Set ZK_HOSTS variable
      set_fact:
        ZK_HOSTS: "{% for host in zookeeper_hosts %}{{ host.host }}:{{ client_port }}{% if not loop.last %},{% endif %}{% endfor %}"
  roles:
    - { role: "../roles/ansibleshipyard.ansible-zookeeper" }

- name: Install solr
  hosts: solr
  become: yes
  vars:
    solr_intergrations: "none"
    solr_cloud: true
    solr_version: "7.6.0"
    solr_dest_main_path: "/opt"
    solr_dest_solr_path: "{{ solr_dest_main_path }}/solr-{{ solr_version }}"
    solr_java_xms: "6G"
    solr_java_xmx: "6G"
    solr_insh_default: "/etc/default/solr.in.sh"
    solr_base_path: "/opt/solr-data"
  roles:
    - { role: "../roles/solr-standalone" }
