---
- name: Update all packages
  package:
    name: '*'
    state: latest

- name: Install EPEL
  package:
    name: "epel-release"
    state: latest

- name: Install Necessary Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - unzip
    - awscli

- name: Create the Vault Group
  group:
    name: vault
    gid: 987
    system: yes

- name: Create the Vault User
  user:
    name: vault
    uid: 987
    system: yes
    group: vault
    createhome: no
    home: /opt/vault/
    shell: /sbin/nologin
    comment: A service account to run Vault

- name: Install Vault
  block:
    - name: Download Vault
      get_url:
        url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
        dest: "{{ vault_download_default_path }}/vault_{{ vault_version }}_linux_amd64.zip"
        owner: root
        group: root
        mode: 0744
        seuser: system_u
        serole: object_r
        setype: usr_t
        selevel: s0
        checksum: "{{ vault_version_checksum }}"

    - name: Create Vault Main Folder
      file:
        path: "{{ vault_root_dir }}"
        state: directory
        owner: root
        group: vault
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: usr_t
        selevel: s0
     
    - name: Create Vault Bin Folder
      file:
        path: "{{ vault_bin_dir }}"
        state: directory
        owner: root
        group: vault
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: bin_t
        selevel: s0

    - name: Unarchive Vault
      unarchive:
        src: "{{ vault_download_default_path }}/vault_{{ vault_version }}_linux_amd64.zip"
        dest: "{{ vault_bin_dir }}"
        remote_src: True

    - name: Set Vault Permissions
      file:
        path: "{{ vault_bin_dir }}/vault"
        state: file
        owner: root
        group: vault
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: bin_t
        selevel: s0

- name: Create Vault Additional Folders
  block:
    - name: Configuration Folder
      file:
        path: "{{ vault_configuration_dir }}"
        state: directory
        owner: root
        group: vault
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: etc_t
        selevel: s0

    - name: SSL Folder
      file:
        path: "{{ vault_tls_configuration_dir }}"
        state: directory
        owner: root
        group: vault
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: cert_t
        selevel: s0

- name: Add Vault Environment Variables
  template:
    src: vault.sh.j2
    dest: /etc/profile.d/vault.sh
    owner: root
    group: vault
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: bin_t
    selevel: s0

- name: Add Vault systemd Service
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: vault
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t
    selevel: s0


- name: Allow Vault to Lock Memory
  capabilities:
    state: present
    path: "{{ vault_bin_dir }}/vault"
    capability: cap_ipc_lock=+ep
