---
- name: Assign capacity reservaton to instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    capacity_reservation_id: "{{ lookup('env', 'CAPACITY_RESERVATION_ID') }}"

  roles:
    - role: "../roles/deployment/capacity-reservation-prepare"
      when: capacity_reservation_id is defined and (capacity_reservation_id | length > 0)
