---
- name: User notificatons via SkyBot or Teams
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    status: "{{ lookup('env', 'DEPLOY_STATUS') }}"
    start_message: "{{ hybris_deploy_version }} deploy on {{ environment_name }} started. Please see {{ job_link }} for more info."
    stop_message:  "{{ hybris_deploy_version }} deploy on {{ environment_name }} was successful. Please see {{ job_link }} for more info."

  tasks:
    - name: Notify users about deployment status
      include_tasks: notify_task.yaml
      vars:
        notification_message: "{{ start_message if status == 'start' else stop_message if status == 'stop' }}"
