root_password          = "dai4ovenoo3shei1Fouk"
address_validation_url = "address-validation-ua-dev.hybris.eia.amway.net"
path_to_ssh_key        = "/Users/admin/Amway/epam-se.pem"
microservice_db_user   = "address_user"
microservice_db_pass   = "address_pass"
