---
- name: Install packages to work with s3
  block:
   - name: Enable EPEL repository
     package:
       name: '{{ epel_url_rpm }}'
       state: present

   - name: Install python2-pip
     package:
       name: python2-pip
       state: present

   - name: Install boto packages
     pip:
       name: '{{ item }}'
     loop: '{{ boto_packages }}'
  become: true
