CREATE DATABASE test_auto_db;                                                                                                  
--- you can find password in the vault under amway/databases/mysql/autoaqa section
CREATE USER 'hybris'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON `test_auto_db`.* TO 'hybris'@'%';
FLUSH PRIVILEGES;
USE test_auto_db;

CREATE TABLE `ENVIRONMENTS` (
  `ENV_NAME` varchar(100) NOT NULL,
  `COUNTRY_CODE` varchar(100) DEFAULT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USERS` (
  `ROLE` varchar(100) DEFAULT NULL,
  `FIRST_NAME` varchar(100) DEFAULT NULL,
  `LAST_NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ABO_NUMBER` bigint(19) NOT NULL,
  `SPONSOR_FIRST_NAME` varchar(100) DEFAULT NULL,
  `SPONSOR_LAST_NAME` varchar(100) DEFAULT NULL,
  `SPONSOR_ABO_NUMBER` bigint(19) DEFAULT NULL,
  `PARTY_ID` bigint(19) DEFAULT NULL,
  `TESTCASE_ID` varchar(100) DEFAULT NULL,
  `ENV_PK` int(11) DEFAULT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` date NOT NULL,
  `IS_AVAILABLE` tinyint(1) NOT NULL DEFAULT '1',
  `ABO_PASSWORD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`PK`),
  KEY `USERS_ENVIRONMENTS_FK` (`ENV_PK`),
  CONSTRAINT `USERS_ENVIRONMENTS_FK` FOREIGN KEY (`ENV_PK`) REFERENCES `ENVIRONMENTS` (`PK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ALIAS` int(11) NOT NULL,
  `PRODUCT_CODE` varchar(100) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `PRICE` varchar(100) DEFAULT NULL,
  `HYBRIS_PK` varchar(100) DEFAULT NULL,
  `PRODUCT_CATALOG` varchar(100) DEFAULT NULL,
  `BASE_PRODUCT_PK` varchar(100) DEFAULT NULL,
  `BASE_PRODUCT_NAME` varchar(100) DEFAULT NULL,
  `STOCK_LEVEL` int(11) DEFAULT NULL,
  `ORDERING_NUMBER` varchar(100) DEFAULT NULL,
  `CATEGORY` varchar(100) DEFAULT NULL,
  `CATEGORY_ID` varchar(100) DEFAULT NULL,
  `SUBCATEGORY` varchar(100) DEFAULT NULL,
  `SUBCATEGORY_ID` varchar(100) DEFAULT NULL,
  `PRICE_WITHOUT_DISCOUNT` varchar(100) DEFAULT NULL,
  `WAREHOUSE` varchar(100) DEFAULT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ORDERS` (
  `ORDER_NUMBER` int(11) NOT NULL,
  `RETURN_NUMBER` int(11) DEFAULT NULL,
  `IS_FULL_RETURN` tinyint(1) DEFAULT NULL,
  `IS_SHIPPING_REQUIRED` tinyint(1) DEFAULT NULL,
  `ORDER_GRAND_TOTAL` varchar(100) DEFAULT NULL,
  `ORDER_TOTAL` varchar(100) DEFAULT NULL,
  `ORDER_TOTAL_PAYMENT` varchar(100) DEFAULT NULL,
  `CART_PV` int(11) DEFAULT NULL,
  `SUBCART_PV` int(11) DEFAULT NULL,
  `CART_BV` int(11) DEFAULT NULL,
  `SUBCART_BV` int(11) DEFAULT NULL,
  `TOTAL_PV` int(11) DEFAULT NULL,
  `TOTAL_BV` int(11) DEFAULT NULL,
  `DELIVERY_NOTE` varchar(100) DEFAULT NULL,
  `COUNTRY_CODE` varchar(100) DEFAULT NULL,
  `USER_NAME` varchar(100) DEFAULT NULL,
  `ABO_NUMBER` int(11) DEFAULT NULL,
  `TRANSACTION_ID` varchar(100) DEFAULT NULL,
  `PAYMENT_METHOD` varchar(100) DEFAULT NULL,
  `IS_FIRST_ORDER` tinyint(1) DEFAULT NULL,
  `NUMBER_OF_SUBORDERS` int(11) DEFAULT NULL,
  `IS_PAYMENT_METHOD_ONLINE` tinyint(1) DEFAULT NULL,
  `ENV_PK` int(11) DEFAULT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  `USERS_PK` int(11) NOT NULL,
  `CREATION_DATE` date NOT NULL,
  `IS_AVAILABLE` tinyint(1) NOT NULL DEFAULT '1',
  `ORDER_STATUS` varchar(100) DEFAULT NULL,
  `DELIVERY_STATUS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`PK`),
  KEY `ORDERS_USERS_FK` (`USERS_PK`),
  KEY `ORDERS_ENVIRONMENTS_FK` (`ENV_PK`),
  CONSTRAINT `ORDERS_ENVIRONMENTS_FK` FOREIGN KEY (`ENV_PK`) REFERENCES `ENVIRONMENTS` (`PK`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ORDERS_USERS_FK` FOREIGN KEY (`USERS_PK`) REFERENCES `USERS` (`PK`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ORDERS_PRODUCTS` (
  `ORDER_PK` int(11) NOT NULL,
  `PRODUCT_PK` int(11) NOT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK`),
  KEY `ORDERS_PRODUCTS_ORDERS_FK` (`ORDER_PK`),
  KEY `ORDERS_PRODUCTS_PRODUCTS_FK` (`PRODUCT_PK`),
  CONSTRAINT `ORDERS_PRODUCTS_ORDERS_FK` FOREIGN KEY (`ORDER_PK`) REFERENCES `ORDERS` (`PK`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ORDERS_PRODUCTS_PRODUCTS_FK` FOREIGN KEY (`PRODUCT_PK`) REFERENCES `PRODUCTS` (`PK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RETURNS` (
  `ORDER_NUMBER` int(11) NOT NULL,
  `USER_NAME` varchar(100) DEFAULT NULL,
  `USER_NUMBER` int(11) NOT NULL,
  `COUNTRY_CODE` varchar(100) DEFAULT NULL,
  `RETURN_TOTAL` varchar(100) DEFAULT NULL,
  `RETURN_GRAND_TOTAL` varchar(100) DEFAULT NULL,
  `RETURN_NUMBER` int(11) NOT NULL,
  `ENV_PK` int(11) NOT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  `ORDERS_PK` int(11) NOT NULL,
  PRIMARY KEY (`PK`),
  KEY `RETURNS_ORDERS_FK` (`ORDER_NUMBER`),
  KEY `RETURN_ORDER_FK` (`ORDERS_PK`),
  KEY `RETURNS_ENVIRONMENTS_FK` (`ENV_PK`),
  CONSTRAINT `RETURNS_ENVIRONMENTS_FK` FOREIGN KEY (`ENV_PK`) REFERENCES `ENVIRONMENTS` (`PK`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `RETURN_ORDER_FK` FOREIGN KEY (`ORDERS_PK`) REFERENCES `ORDERS` (`PK`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `WRONG_ALIASES` (
  `PRODUCT_ALIAS` varchar(100) NOT NULL,
  `ENV_PK` int(11) NOT NULL,
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK`),
  KEY `WRONG_ALIASES_ENVIRONMENTS_FK` (`ENV_PK`),
  CONSTRAINT `WRONG_ALIASES_ENVIRONMENTS_FK` FOREIGN KEY (`ENV_PK`) REFERENCES `ENVIRONMENTS` (`PK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
