---
- hosts: all
# Just to make things easy
  pre_tasks:
    - name: "Disable Selinux"
      become: True
      selinux:
        state: "disabled"
  roles:
  - role: '../roles/lean_delivery.mysql'
    mysql_root_password: "LKJnk3542390jMJhoipjmrg"
    mysql_root_username: "root"
    mysql_user_home: "/home/centos"
    mysql_user_name: "centos"
    mysql_user_password: "centos"
    mysql_databases:
      - name: "hybris"   
    mysql_users:
      - name: "hybris"
        host: ""
        password: "hybris"
        priv: "hybris.*:ALL,GRANT"
    mysql_daemon: "mysqld"
    mysql_version: "5.6"
    mysql_max_allowed_packet: "16384K"
    mysql_query_cache_type: "1"
    mysql_innodb_flush_log_at_trx_commit: "0"
    mysql_innodb_buffer_pool_size: "{{ ((ansible_memtotal_mb-4096)*0.8)|int|abs }}M"
    mysql_max_connections: "400"
    mysql_key_buffer_size: "81920K"
    mysql_read_buffer_size: "1280K"
    mysql_table_open_cache: "400"
    mysql_slow_query_time: "10" 
    mysql_log_error: "/var/log/mysqld.log"
    additional_parameters:
      - name: lc-messages-dir
        value: "/usr/share/mysql"
      - name: thread_stack
        value: "192K"
      - name: character_set_server
        value: "utf8"
      - name: sync_binlog
        value: "0"
      - name: transaction_isolation
        value: "REPEATABLE-READ"
      - name: innodb_buffer_pool_instances
        value: "8"
      - name: innodb_purge_threads
        value: "4"
      - name: innodb_flush_method
        value: "O_DIRECT"
      - name: innodb_io_capacity_max
        value: "300"
      - name: innodb_io_capacity
        value: "250"

  post_tasks:
   - name: install wget and unzip
     become: True
     yum:
       name: "{{ item.name }}"
       state: "{{ item.version }}"
     loop:
       - { name: 'wget', version: 'latest' }
       - { name: 'unzip', version: 'latest' }
