---
- name: Download and unpack zip archive
  become: True
  block:
    - name: Create dest dir for file download
      file:
        path: /root/solrconfig
        state: directory
    - name: Download zip archive
      get_url:
        url: "{{ solr_config_zip_address }}"
        dest: /root/solrconfig/hybrisServer-Config.zip
      register: config_zip_downloaded
      until: config_zip_downloaded is succeeded
      retries: 5
      delay: 5
  rescue:
    - name: Notify about failure
      include_tasks: notify.yaml
      vars:
        notification_message: "{{ hybris_deploy_version }} deploy on {{ environment_name }} failed. Failed to download config zip archive from nexus server"

    - name: Now fail real
      fail:
        msg: "Failed to download zip archive"

- name: Unpack artifact
  become: True
  block:
    # You may ask why not to use unarchive module
    # Time to unarchive zip file using module ~ 5-6 min
    - name: Unarchive zip archive
      command: "unzip -o -qq /root/solrconfig/hybrisServer-Config.zip -d /root/solrconfig/"

    - name: Delete zip archive
      file:
        path: /root/solrconfig/hybrisServer-Config.zip
        state: absent
  rescue:
    - name: Notify about failure
      include_tasks: notify.yaml
      vars:
        notification_message: "{{ hybris_deploy_version }} deploy on {{ environment_name }} failed. Could not unpack hybris config zip archive"

    - name: Now fail real
      fail:
        msg: "Could not unpack hybris config zip archive"
