name: Demo cluster - destroy

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  cluster_addons:
    uses: AmwayCommon/jp-cicd-workflows/.github/workflows/aws-iac-destroy.yml@v0
    with:
      project_dir: projects/demo/stacks/cluster-addons

  cluster_network:
    needs: cluster_addons
    uses: AmwayCommon/jp-cicd-workflows/.github/workflows/aws-iac-destroy.yml@v0
    with:
      project_dir: projects/demo/stacks/cluster-network

  cluster_infra:
    needs: [cluster_addons, cluster_network]
    uses: AmwayCommon/jp-cicd-workflows/.github/workflows/aws-iac-destroy.yml@v0
    with:
      project_dir: projects/demo/stacks/cluster-infra
