name: Production BNC Training Data DynamoDB IAM role

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  PROJECT_DIR: projects/jp-acsd-bnc-training-data/stacks/production

jobs:
  deploy_role:
    name: Deploy the IAM role
    runs-on: jpn-automation-dev
    steps:
      - name: Install tools
        run: sudo apt update && sudo apt install -y curl unzip make gawk git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::492449516969:role/jp-cicd-automation-infra
          role-session-name: github
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5

      - name: Setup project
        working-directory: ${{ env.PROJECT_DIR }}
        run: make init
      - name: Plan
        working-directory: ${{ env.PROJECT_DIR }}
        run: make plan
      - name: Apply
        working-directory: ${{ env.PROJECT_DIR }}
        run: make apply
