name: Build container image for Inventory Recon jobs

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - feature/recon-runner

permissions:
  id-token: write
  contents: read

jobs:
  build_image:
    uses: AmwayCommon/jp-cicd-workflows/.github/workflows/image-build-push-ecr.yml@v0
    with:
      iam_role: arn:aws:iam::492449516969:role/jp-hybris-prd-reconciliation-artifacts
      ecr_repository: 492449516969.dkr.ecr.ap-northeast-1.amazonaws.com/jp-hybris-prd-reconciliation-runner
      image_tag: v1
      dockerfile: projects/jp-hybris-reconciliation-resources/docker/Dockerfile
      context: projects/jp-hybris-reconciliation-resources/docker
    secrets: inherit
