name: Custom test run by parameters

on:
  workflow_dispatch:
    inputs:
      country:
        type: choice
        description: "Country name"
        required: true
        default: finland
        options:
          - finland
          - sweden
          - denmark
          - norway
          - spain
          - portugal
          - netherlands
          - belgium
          - italy
          - germany
          - france
          - switzerland
          - austria
          - turkey
          - poland
          - greece
          - romania
          - croatia
          - czech_republic
          - slovenia
          - slovakia
          - estonia
          - latvia
          - lithuania
          - bulgaria
          - hungary
          - united_kingdom
          - ireland
          - ukraine
          - mongolia
          - kazakhstan
          - kyrgyzstan
          - russia
          - botswana
          - namibia
          - south_africa

      test:
        description: "Test type (def: smoke)"
        required: true
        default: smoke

      environment:
        description: "Environment name (def: ultraserve_fqa)"
        required: true
        default: ultraserve_fqa

      cucumber_filter_tags:
        description: "Provide Dcucumber.filter.tags without quotes"
        required: true
        default: ""

      cycle:
        description: "Optional: Cycle key in JIRA (i.e. 'AMWEIA-C15696')"
        required: false

env:
  ECR_REGISTRY: "744058822102.dkr.ecr.eu-central-1.amazonaws.com"
  DOCKER_CONFIG: "/home/github/.docker"
  # Static vars
  BROWSER: chrome
  REPORT_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin

  # User input
  COUNTRY: ${{ github.event.inputs.country }}
  TEST: ${{ github.event.inputs.test }}
  CUCUMBER_TAGS: ${{ github.event.inputs.cucumber_filter_tags }}
  ENV: ${{ github.event.inputs.environment }}
  CYCLE: ${{ github.event.inputs.cycle }}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  # Reports related vars
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}
  REPORT_URL: "https://allure-reports.hybris.eu.eia.amway.net"

# Jobs for multiple countries (exec in parallel)
jobs:
  run_test:
    name: Custom Tests run (t3a.xlarge)
    runs-on: [ self-hosted, t3a.xlarge ]
    timeout-minutes: 180

    steps:
      - name: Print command
        shell: bash
        run: |
          echo "Going to run $CUCUMBER_TAGS for $COUNTRY"

      - name: Helper step
        shell: bash
        run: |
          # Print ip address of the agent which took the job
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"

          # Used as a working directory with src code within it
          CODEBASE="${GITHUB_REPOSITORY##*/}"
          # Workflow name will be used to upload artifacts to s3
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          # S3 bucket url to upload artifact
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"

          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV

      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}


      - name: Maven execute
        shell: bash
        env:
          DISPLAY: ":1.0"
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn clean install -P$TEST -Denv=$ENV -Dcountry=$COUNTRY -Dbrowser=$BROWSER -Dcucumber.filter.tags="$CUCUMBER_TAGS" -Dcycle="$CYCLE"

      - name: Maven generate allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn allure:report

      - name: Try to upload allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ -d $REPORT_DIR ]; then
              echo Going to upload report to s3
              aws s3 cp --quiet --recursive $REPORT_DIR $S3_FULL_URL
              echo "ARTIFACT_UPLOADED=yes" >> $GITHUB_ENV
              echo Report was uploaded
          else
              echo Reports dir NOT FOUND
              echo "ARTIFACT_UPLOADED=no" >> $GITHUB_ENV
              exit 0
          fi

      - name: Summary
        if: ${{ always() }}
        shell: bash
        run: |
          if [ $ARTIFACT_UPLOADED != 'yes' ]; then
              echo "Allure report was not uploaded"
              echo "Please check logs of previous steps"
          else
            echo "Allure report is ready --> $REPORT_URL/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"
          fi

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf
