name: Custom test run by command

on:
  workflow_dispatch:
    inputs:
      mvn_args:
        description: "Provide arguments for maven binary"
        required: true
        default: "clean install -Psmoke -Denv=ultraserve_fqa -Dcountry=finland -Dbrowser=chrome"
      cucumber_filter_tags:
        description: "Provide Dcucumber.filter.tags without quotes"
        required: true
        default: ""
      cycle:
        description: "Optional: Cycle key in JIRA (i.e. 'AMWEIA-C15696')"
        required: false

env:
  ECR_REGISTRY: "744058822102.dkr.ecr.eu-central-1.amazonaws.com"
  DOCKER_CONFIG: "/home/github/.docker"
  # Static vars
  REPORT_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin
  ARTIFACTS_DIR: ../b2c_ootb/target/allure-results

  # User input
  MVN_ARGS: ${{ github.event.inputs.mvn_args }}
  CUCUMBER_TAGS: ${{ github.event.inputs.cucumber_filter_tags }}
  CYCLE: ${{ github.event.inputs.cycle }}

  # Reports related vars
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}
  REPORT_URL: "https://allure-reports.hybris.eu.eia.amway.net"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run_test:
    name: Run by maven Cmd (t3a.xlarge)
    runs-on: [ self-hosted, t3a.xlarge ]
    timeout-minutes: 180

    steps:
      - name: Print maven cmd
        shell: bash
        run: |
          if [ "$CUCUMBER_TAGS" = "" ]; then
              echo
              echo "Maven cmd to execute: mvn -B $MVN_ARGS"
              echo
          else
              echo
              echo "Maven cmd to execute: mvn -B $MVN_ARGS -Dcucumber.filter.tags=\"$CUCUMBER_TAGS\" -Dcycle=\"$CYCLE\""
              echo
          fi

      - name: Helper step
        shell: bash
        run: |
          # Print ip address of the agent which took the job
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"

          # Used as a working directory with src code within it
          CODEBASE="${GITHUB_REPOSITORY##*/}"
          # Workflow name will be used to upload artifacts to s3
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          # S3 bucket url to upload artifact
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"

          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV

      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}


      - name: Maven execute
        shell: bash
        env:
          DISPLAY: ":1.0"
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ "$CUCUMBER_TAGS" = "" ]; then
              mvn -B $MVN_ARGS
          else
              mvn -B $MVN_ARGS -Dcucumber.filter.tags="$CUCUMBER_TAGS" -Dcycle="$CYCLE"
          fi

      - name: Maven generate allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn allure:report

      - name: Try to upload allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ -d $REPORT_DIR ]; then
              echo Going to upload report to s3
              aws s3 cp --quiet --recursive $REPORT_DIR $S3_FULL_URL
              echo "ARTIFACT_UPLOADED=yes" >> $GITHUB_ENV
              echo Report was uploaded
          else
              echo Reports dir NOT FOUND
              echo "ARTIFACT_UPLOADED=no" >> $GITHUB_ENV
              exit 0
          fi

      - name: Summary
        if: ${{ always() }}
        shell: bash
        run: |
          echo
          echo "Executed cmd: mvn -B $MVN_ARGS"
          echo

          if [ $ARTIFACT_UPLOADED != 'yes' ]; then
              echo "Allure report was not uploaded"
              echo "Please check logs of previous steps"
          else
            echo "Allure report is ready --> $REPORT_URL/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"
          fi

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf
