name: FQA KZ Scheduled Config Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: 00 5 * * 1-5

# global env set
env:
  ECR_REGISTRY: "744058822102.dkr.ecr.eu-central-1.amazonaws.com"
  DOCKER_CONFIG: "/home/github/.docker"
  TEST: configSmoke
  BROWSER: chrome
  ENV: ultraserve_fqa_kz
  REPORT_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin
  REPORT_HISTORY_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin/history

  # reports related vars
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}
  REPORT_URL: "https://allure-reports.hybris.eu.eia.amway.net"

  # actions related vars
  ACTIONS_REPO: AmwayCommon/actions

  # notifications related vars
  SMTP_SERVER: relay.hybris.eu.eia.amway.net
  RCPTS: Amway.EU.AQA@Amway.com
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

# jobs
jobs:
  history:
    name: History cleaning
    runs-on: [ self-hosted, t3a.large ]
    timeout-minutes: 180
    if: ${{ always() }}

    env:
      INCLUDE_TEST: "AllureReportsHistoryFilter"

    steps:
      - name: Helper step
        shell: bash
        run: |
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"
          CODEBASE="${GITHUB_REPOSITORY##*/}"
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"
          HISTORY_DIR="./history"
          S3_HISTORY_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/history"
          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV
          echo "HISTORY_DIR=$HISTORY_DIR" >> $GITHUB_ENV
          echo "S3_HISTORY_URL=$S3_HISTORY_URL" >> $GITHUB_ENV
      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Checkout ${{ env.ACTIONS_REPO }} repo
        uses: actions/checkout@v4
        with:
          path: actions
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ env.ACTIONS_REPO }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
      - name: Check and copy previously-saved history folder to project dir
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mkdir $HISTORY_DIR
          aws s3 cp --recursive $S3_HISTORY_URL $HISTORY_DIR
          if [ -z "$(ls -A $HISTORY_DIR)"]; then
            echo there is NO history FOUND for this workflow
          else
            echo this workflow history is copied from $S3_HISTORY_URL
          fi
      - name: Maven execute
        shell: bash
        env:
          DISPLAY: ":1.0"
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn -e clean install -Dbrowser=$BROWSER \
                               -DfailIfNoTests=$FAIL_IF_NO_TESTS \
                               -PdataGenerator \
                               -Dcountry=$COUNTRY \
                               -Denv=$TEST_ENVIRONMENT \
                               -Dtest=$INCLUDE_TEST
      - name: Try to upload filtered history back to s3
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ -z "$(ls -A $HISTORY_DIR)"]; then
              echo History dir of report NOT FOUND
              echo "HISTORY_UPLOADED=no" >> $GITHUB_ENV
              exit 0
          else
              echo Going to upload filtered history to s3
              aws s3 cp --quiet --recursive $HISTORY_DIR $S3_HISTORY_URL
              echo "HISTORY_UPLOADED=yes" >> $GITHUB_ENV
              echo History was uploaded
          fi
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf

  config:
    name: Run config tests for Kazakhstan (t3a.xlarge)
    runs-on: [self-hosted, t3a.xlarge ]
    needs: [ history ]

    env:
      COUNTRY: kazakhstan
      TAGS: "@Config and @ri5 and not @excluded"
    outputs:
      allure_addr: ${{ steps.summary.outputs.url }}

    steps:
      - name: Helper step
        shell: bash
        run: |
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"
          CODEBASE="${GITHUB_REPOSITORY##*/}"
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"
          ALLURE_RESULTS_HISTORY_DIR="b2c_ootb/target/allure-results/history"
          S3_HISTORY_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/history"

          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV
          echo "ALLURE_RESULTS_HISTORY_DIR=$ALLURE_RESULTS_HISTORY_DIR" >> $GITHUB_ENV
          echo "S3_HISTORY_URL=$S3_HISTORY_URL" >> $GITHUB_ENV

      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Checkout ${{ env.ACTIONS_REPO }} repo
        uses: actions/checkout@v4
        with:
          path: actions
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ env.ACTIONS_REPO }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}


      - name: Maven execution
        shell: bash
        env:
          DISPLAY: ":1.0"
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn clean install -P$TEST -Denv=$ENV -Dbrowser=$BROWSER -Dcountry=$COUNTRY -Dcucumber.filter.tags="$TAGS"

      - name: Check and copy previously-saved history folder to allure-results
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          cd $ARTIFACTS_DIR
          mkdir history
          aws s3 cp --recursive $S3_HISTORY_URL ./history
          if [ -z "$(ls -A ./history)"]; then
            echo there is NO history FOUND for this workflow
          else
            echo this workflow history is copied
          fi

      - name: Generate allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn -B allure:report

      - name: Try to upload allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ -d $REPORT_DIR ]; then
              echo Going to upload report to s3
              aws s3 cp --quiet --recursive $REPORT_DIR $S3_FULL_URL
              echo "ARTIFACT_UPLOADED=yes" >> $GITHUB_ENV
              echo Report was uploaded
          else
              echo Reports dir NOT FOUND
              echo "ARTIFACT_UPLOADED=no" >> $GITHUB_ENV
              exit 0
          fi

      - name: Try to upload history of allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ -d $REPORT_HISTORY_DIR ]; then
              ls -A $REPORT_HISTORY_DIR
              echo Going to upload report history to s3
              aws s3 cp --quiet --recursive $REPORT_HISTORY_DIR $S3_HISTORY_URL
              echo "HISTORY_UPLOADED=yes" >> $GITHUB_ENV
              echo History was uploaded
          else
              echo History dir of report NOT FOUND
              tmpVar=$(ls $REPORT_DIR)
              echo "Showing Report directory structure: $tmpVar"
              echo "HISTORY_UPLOADED=no" >> $GITHUB_ENV
              exit 0
          fi


      - name: Summary
        if: ${{ always() }}
        id: summary
        shell: bash
        run: |
          if [ $ARTIFACT_UPLOADED != 'yes' ]; then
              echo "Allure report was not uploaded"
              echo "Please check logs of previous steps"
          else
            echo "Allure report is ready --> $REPORT_URL/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER/"
            echo "::set-output name=url::$REPORT_URL/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER/"
          fi

      - name: Notify after completion (email media)
        if: ${{ always() }}
        uses: "./actions/send-email"
        with:
          smtp_server: ${{ env.SMTP_SERVER }}
          rcpts: ${{ env.RCPTS}}
          subj: "${{ github.workflow }} #${{ github.run_number}} COMPLETED"
          to: Amway.EU.AQA@Amway.com
          msg: |
            <h1> ${{ github.workflow }} ${{ github.run_number}} COMPLETED</h1>
            <p><a href='${{ env.REPORT_URL }}/${{ env.WORKFLOW_NAME }}/N${{ github.run_number }}'>Allure Report</a></p>

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf
