name: Hybris Tests EU by Epic and Country

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment name"
        required: true
        default: ultraserve_fqa
        options:
          - ultraserve_fqa
          - ultraserve_uat
          - ultraserve_nft
          - ultraserve_stg
          - uat1
          - uat2
          - uat3
          - uat4
          - fqa1
          - fqa2
          - fqa3
          - fqa4

      country:
        type: choice
        description: "Country name"
        required: true
        default: finland
        options:
          - finland
          - sweden
          - denmark
          - norway
          - spain
          - portugal
          - netherlands
          - belgium
          - italy
          - germany
          - france
          - switzerland
          - austria
          - turkey
          - poland
          - greece
          - romania
          - croatia
          - czech_republic
          - slovenia
          - slovakia
          - estonia
          - latvia
          - lithuania
          - bulgaria
          - hungary
          - united_kingdom
          - ireland

      epic:
        type: choice
        description: "Epic number"
        required: true
        default: 040_Single_orders
        options:
          - 01_Products
          - 02_Order_data
          - 03_Registration
          - 040_Single_orders
          - 041_Multicart_orders
          - 042_GCO_orders
          - 043_Country_cpecific_orders
          - 044_Cancel_orders
          - 045_Promotions_orders
          - 046_Copy_order
          - 047_Checkout_edit_address
          - 05_My_account
          - 06_Customer_model
          - 11_Returns
          - 12_ASM

      cycle:
        description: "Optional: Cycle key in JIRA (i.e. 'AMWEIA-C15696')"
        required: false

env:
  ECR_REGISTRY: "744058822102.dkr.ecr.eu-central-1.amazonaws.com"
  DOCKER_CONFIG: "/home/github/.docker"
  # Tests related vars
  BROWSER: chrome
  COUNTRY: ${{ github.event.inputs.country }}
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  EPIC: ${{ github.event.inputs.epic }}
  TEST_RUN_ID: ""
  ARTIFACTS_DIR: b2c_ootb/target/allure-results
  REPORT_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin
  REPORT_HISTORY_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin/history

  # Reports related vars
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}
  REPORT_URL: "https://allure-reports.hybris.eu.eia.amway.net"
  CYCLE: ${{ github.event.inputs.cycle }}

  # actions related vars
  ACTIONS_REPO: AmwayCommon/actions

  # Notifications related vars
  SMTP_SERVER: relay.hybris.eu.eia.amway.net
  RCPTS: Amway.EU.AQA@Amway.com
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
jobs:
  job_01:
    name: Epic execution (t3a.xlarge)
    runs-on: [ self-hosted, t3a.xlarge ]
    timeout-minutes: 180

    env:
      JOB_NUM: 01

    steps:
      - name: Helper step
        shell: bash
        run: |
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"

          CODEBASE="${GITHUB_REPOSITORY##*/}"
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"

          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV

      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}


      - name: Maven execute
        shell: bash
        env:
          DISPLAY: ":1.0"
        working-directory: ${{ env.CODEBASE }}
        run: |
          RI1_COUNTRIES=(finland sweden denmark norway)
          RI2_COUNTRIES=(spain portugal netherlands belgium)
          RI3_COUNTRIES=(italy germany switzerland austria france)
          RI4_COUNTRIES=(turkey poland greece romania croatia czech_republic slovenia slovakia estonia latvia lithuania bulgaria hungary united_kingdom ireland)

          # if ri1 group
          if printf '%s\n' "${RI1_COUNTRIES[@]}" | grep -q -P $COUNTRY; then
          ROLL_IN="ri1"
          # elif ri2 group
          elif printf '%s\n' "${RI2_COUNTRIES[@]}" | grep -q -P $COUNTRY; then
          ROLL_IN="ri2"
           # elif ri3 group
          elif printf '%s\n' "${RI3_COUNTRIES[@]}" | grep -q -P $COUNTRY; then
          ROLL_IN="ri3"
           # elif ri4 group
          elif printf '%s\n' "${RI4_COUNTRIES[@]}" | grep -q -P $COUNTRY; then
          ROLL_IN="ri4"
          else
          echo "Error: country not in the RI list"
          fi
          
          if [ "01_Products" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_01"
          EXCLUDE_TEST="@excluded"
          elif [ "02_Order_data" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_02"
          EXCLUDE_TEST="@excluded"
          elif [ "03_Registration" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_03"
          EXCLUDE_TEST="@excluded"
          elif [ "040_Single_orders" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @SingleOrder)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "041_Multicart_orders" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @MultiCart)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "042_GCO_orders" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @Gco)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "043_Country_cpecific_orders" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @CountrySpecificOrders)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "044_Cancel_orders" = "$EPIC" ]; then
          INCLUDE_TEST="(@CancelOrder and @hybris_eu)"
          EXCLUDE_TEST="@excluded"
          elif [ "045_Promotions_orders" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @Promo)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "046_Copy_order" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @CopyOrder)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "047_Checkout_edit_address" = "$EPIC" ]; then
          INCLUDE_TEST="(@Hybris_04 and @OrderEditAddress)"
          EXCLUDE_TEST="(@CancelOrder or @excluded)"
          elif [ "05_My_account" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_05"
          EXCLUDE_TEST="@excluded"
          elif [ "06_Customer_model" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_06"
          EXCLUDE_TEST="@excluded"
          elif [ "11_Returns" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_11"
          EXCLUDE_TEST="@excluded"
          elif [ "12_ASM" = "$EPIC" ]; then
          INCLUDE_TEST="@Hybris_12"
          EXCLUDE_TEST="@excluded"
          else
          echo "Error: Provided epic doesn't match to expected values"
          fi
          
          if [ "044_Cancel_orders" = "$EPIC" ]; then
          PROFILE="singleThread"
          else
          PROFILE="regression"
          fi
          
          echo "$INCLUDE_TEST $ROLL_IN $COUNTRY"
          mvn clean install -Dbrowser=$BROWSER \
                            -P$PROFILE \
                            -Dcountry=$COUNTRY \
                            -Denv=$ENVIRONMENT \
                            -DtestRunId=$TEST_RUN_ID \
                            -Dcycle=$CYCLE \
                            -Dcucumber.filter.tags="$INCLUDE_TEST and (@$COUNTRY or @$ROLL_IN) and not $EXCLUDE_TEST"

      - name: Try to upload allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          # Try to copy allure report
          if [ -d $ARTIFACTS_DIR ]; then
              mkdir -p allure
              for i in $ARTIFACTS_DIR/*; do cp -rf "$i" allure; done
          else
              echo Reports dir NOT FOUND
              exit 0
          fi

          # Upload allure report to s3
          tar -zcf allure_$JOB_NUM.tar.gz allure
          aws s3 cp  allure_$JOB_NUM.tar.gz  $S3_FULL_URL/allure_$JOB_NUM.tar.gz

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf

  summary:
    name: Generate results (t3a.medium)
    runs-on: [ self-hosted, t3a.medium ]
    timeout-minutes: 180
    needs: [ job_01 ]
    if: ${{ always() }}

    steps:
      - name: Helper step
        shell: bash
        run: |
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"

          CODEBASE="${GITHUB_REPOSITORY##*/}"
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"
          
          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV

      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Checkout ${{ env.ACTIONS_REPO }} repo
        uses: actions/checkout@v4
        with:
          path: actions
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ env.ACTIONS_REPO }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}


      - name: Download artifacts from the previous steps
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mkdir -p $ARTIFACTS_DIR
          cd $ARTIFACTS_DIR

          # Copy results for s3 to appropriate dir
          aws s3 cp --quiet --recursive  $S3_FULL_URL .
          for file in *.tar.gz; do
              tar -zxf $file
          done

          for x in allure/*; do mv -- "$x" .; done
          rmdir allure

      - name: Generate allure report
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn allure:report

      - name: Upload prepared allure report to s3
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          aws s3 cp --recursive "$REPORT_DIR" $S3_FULL_URL

      - name: Print results of scheduled tests
        shell: bash
        run: |
          echo
          echo "Allure report could be found here: $REPORT_URL/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"

      - name: Notify after completion (email media)
        if: ${{ always() }}
        uses: "./actions/send-email"
        with:
          smtp_server: ${{ env.SMTP_SERVER }}
          rcpts: ${{ env.RCPTS}}
          subj: "${{ github.workflow }} #${{ github.run_number}} COMPLETED"
          to: Amway.EU.AQA@Amway.com
          msg: |
            <h1> ${{ github.workflow }} ${{ github.run_number}} COMPLETED</h1>
            <p>Allure Report for ${{ env.COUNTRY }} could be found <a href='${{ env.REPORT_URL }}/${{ env.WORKFLOW_NAME}}/N${{ github.run_number }}'>here</a> </p>

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf
