name: User Generator

on:
  workflow_dispatch:
    inputs:
      country:
        type: choice
        description: "Country name"
        required: true
        default: finland
        options:
          - finland
          - sweden
          - denmark
          - norway
          - spain
          - portugal
          - netherlands
          - belgium
          - italy
          - germany
          - france
          - switzerland
          - austria
          - turkey
          - poland
          - greece
          - romania
          - croatia
          - czech_republic
          - slovenia
          - slovakia
          - estonia
          - latvia
          - lithuania
          - bulgaria
          - hungary
          - united_kingdom
          - ireland
          - botswana
          - namibia
          - south_africa
          - kazakhstan
          - ukraine

      environment:
        description: "Environment name (i.e: ultraserve_dev)"
        required: true
        default: ultraserve_fqa

      abo_qty:
        description: "ABO without downliners quantity"
        required: true
        default: "1"

      ie_qty:
        description: "IE quantity for UA and KZ"
        required: true
        default: "0"

      customer_qty:
        description: "Customer quantity"
        required: true
        default: "0"

      abo_downliners_abo_qty:
        description: "ABO type downliners quantity for 1 default ABO sponsor"
        required: true
        default: "0"

      abo_downliners_customer_qty:
        description: "Customer type downliners quantity for 1 default ABO sponsor"
        required: true
        default: "0"
#      sponsor_abo_number:
#        description: "Sponsor ABO Number for downliners"
#        required: true
#        default: "0"

env:
  ECR_REGISTRY: "744058822102.dkr.ecr.eu-central-1.amazonaws.com"
  DOCKER_CONFIG: "/home/github/.docker"
  # Static vars
  BROWSER: chrome
  FAIL_IF_NO_TESTS: false
  REPORT_DIR: amway-test-system-ui-tests/target/site/allure-maven-plugin

  # User input
  COUNTRY: ${{ github.event.inputs.country }}
  TEST_ENVIRONMENT: ${{ github.event.inputs.environment }}
  ABO_QTY: ${{ github.event.inputs.abo_qty }}
  IE_QTY: ${{ github.event.inputs.ie_qty }}
  CUSTOMER_QTY: ${{ github.event.inputs.customer_qty }}
  ABO_DOWNLINERS_QTY: ${{ github.event.inputs.abo_downliners_abo_qty }}
  CUSTOMER_DOWNLINERS_QTY: ${{ github.event.inputs.abo_downliners_customer_qty }}
  SPONSOR_ABO_NUMBER: ${{ github.event.inputs.sponsor_abo_number }}

  # Reports related vars
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}
  REPORT_URL: "https://allure-reports.hybris.eu.eia.amway.net"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
# Jobs for multiple countries (exec in parallel)
jobs:
  run_test:
    name: User Generator (t3a.xlarge)
    env:
      INCLUDE_TEST: "UserGenerator"
    runs-on: [ self-hosted, t3a.xlarge ]
    timeout-minutes: 180

    steps:
      - name: Execution info
        shell: bash
        run: |
          echo "Going to run user generator. $ABO_QTY ABO, $IE_QTY and $CUSTOMER_QTY Customers are going to be created for $COUNTRY"
          echo $ABO_DOWNLINERS_QTY downliners with ABO type and $CUSTOMER_DOWNLINERS_QTY downliners with customer are going to be created for 1 ABO
          echo
          echo "mvn clean install -PdataGenerator -DfailIfNoTests=$FAIL_IF_NO_TESTS -Denv=$TEST_ENVIRONMENT -Dcountry=$COUNTRY -Dbrowser=$BROWSER -Dtest=$INCLUDE_TEST -DaboQty=$ABO_QTY -DieQty=$IE_QTY -DcustomerQty=$CUSTOMER_QTY -DaboDownlinersQty=$ABO_DOWNLINERS_QTY -DcustomerDownlinersQty=$CUSTOMER_DOWNLINERS_QTY -DsponsorAboNumber=$SPONSOR_ABO_NUMBER"

      - name: Helper step
        shell: bash
        run: |
          # Print ip address of the agent which took the job
          ip_addr=$(ip --brief a | tail -n1 | awk '{print $3}')
          echo "Agent IP address is: ${ip_addr%/*}"

          # Used as a working directory with src code within it
          CODEBASE="${GITHUB_REPOSITORY##*/}"
          # Workflow name will be used to upload artifacts to s3
          WORKFLOW_NAME=$(echo ${GITHUB_WORKFLOW,,} | sed -e 's:\s:_:g')
          # S3 bucket url to upload artifact
          S3_FULL_URL="s3://$S3_BUCKET_NAME/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"

          # Set usefull env vars for next steps
          echo "CODEBASE=$CODEBASE" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV
          echo "S3_FULL_URL=$S3_FULL_URL" >> $GITHUB_ENV

      - name: Checkout AmwayAutoQA repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.CODEBASE }}

      - name: Login into the AWS ECR registry
        shell: bash
        run: |
          aws ecr get-login-password --region  eu-central-1   | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}


      - name: Maven execute
        shell: bash
        env:
          DISPLAY: ":1.0"
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn clean install -Dbrowser=$BROWSER \
                            -PdataGenerator \
                            -DfailIfNoTests=$FAIL_IF_NO_TESTS \
                            -Denv=$TEST_ENVIRONMENT \
                            -Dcountry=$COUNTRY \
                            -Dtest=$INCLUDE_TEST \
                            -DaboQty=$ABO_QTY \
                            -DieQty=$IE_QTY \
                            -DcustomerQty=$CUSTOMER_QTY \
                            -DaboDownlinersQty=$ABO_DOWNLINERS_QTY \
                            -DcustomerDownlinersQty=$CUSTOMER_DOWNLINERS_QTY \
                            -DsponsorAboNumber=$SPONSOR_ABO_NUMBER

      - name: Maven generate allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          mvn allure:report

      - name: Try to upload allure report
        if: ${{ always() }}
        shell: bash
        working-directory: ${{ env.CODEBASE }}
        run: |
          if [ -d $REPORT_DIR ]; then
              echo Going to upload report to s3
              aws s3 cp --quiet --recursive $REPORT_DIR $S3_FULL_URL
              echo "ARTIFACT_UPLOADED=yes" >> $GITHUB_ENV
              echo Report was uploaded
          else
              echo Reports dir NOT FOUND
              echo "ARTIFACT_UPLOADED=no" >> $GITHUB_ENV
              exit 0
          fi

      - name: Summary
        if: ${{ always() }}
        shell: bash
        run: |
          if [ $ARTIFACT_UPLOADED != 'yes' ]; then
              echo "Allure report was not uploaded"
              echo "Please check logs of previous steps"
          else
            echo "Allure report is ready --> $REPORT_URL/$WORKFLOW_NAME/N$GITHUB_RUN_NUMBER"
          fi

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ env.ECR_REGISTRY }}

      - name: Clean up
        shell: bash
        if: ${{ always() }}
        run: |
          ls -A | xargs -n 1 rm -rf
