---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: epc
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: filebeat-multiline-centos-7-epc
    shape: small
    image: CentOS7_64-bit
    groups:
      - filebeat
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: cloud-epc-el7
verifier:
  name: testinfra
  lint:
    name: flake8
