- name: Update ZabbixAdmin password
  block:
    - name: Copy SQL query to update admin user
      template:
        src: update_admin_password.sql.j2
        dest: /tmp/update_admin_password.sql

    - name: Update Admin Password
      mysql_db:
        login_host: "{{ mysql_server_address }}"
        login_user: "{{ mysql_master_username }}"
        login_password: "{{ mysql_master_password }}"
        name: "{{ mysql_zabbix_database }}"
        state: import
        target: /tmp/update_admin_password.sql

    - name: Delete SQL query to update admin user
      file:
        path: /tmp/update_admin_password.sql
        state: absent
